// Generated by Dagger (https://google.github.io/dagger).
package com.base.mvvm.common.view.base;

import androidx.databinding.ViewDataBinding;
import androidx.fragment.app.Fragment;
import androidx.lifecycle.ViewModel;
import androidx.lifecycle.ViewModelProvider;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.android.support.DaggerDialogFragment_MembersInjector;
import javax.inject.Provider;

public final class BaseDialogFragment_MembersInjector<
        V extends ViewModel, D extends ViewDataBinding>
    implements MembersInjector<BaseDialogFragment<V, D>> {
  private final Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider;

  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  public BaseDialogFragment_MembersInjector(
      Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider,
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    this.childFragmentInjectorProvider = childFragmentInjectorProvider;
    this.viewModelFactoryProvider = viewModelFactoryProvider;
  }

  public static <V extends ViewModel, D extends ViewDataBinding>
      MembersInjector<BaseDialogFragment<V, D>> create(
          Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider,
          Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    return new BaseDialogFragment_MembersInjector<V, D>(
        childFragmentInjectorProvider, viewModelFactoryProvider);
  }

  @Override
  public void injectMembers(BaseDialogFragment<V, D> instance) {
    DaggerDialogFragment_MembersInjector.injectChildFragmentInjector(
        instance, childFragmentInjectorProvider.get());
    injectViewModelFactory(instance, viewModelFactoryProvider.get());
  }

  public static <V extends ViewModel, D extends ViewDataBinding> void injectViewModelFactory(
      BaseDialogFragment<V, D> instance, ViewModelProvider.Factory viewModelFactory) {
    instance.viewModelFactory = viewModelFactory;
  }
}
