// Generated by Dagger (https://google.github.io/dagger).
package com.base.mvvm.common.view.base;

import androidx.databinding.ViewDataBinding;
import androidx.fragment.app.Fragment;
import com.base.mvvm.common.data.local.SharedPrefsHelper;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import javax.inject.Provider;

public final class BaseActivity_MembersInjector<D extends ViewDataBinding>
    implements MembersInjector<BaseActivity<D>> {
  private final Provider<SharedPrefsHelper> appPrefsProvider;

  private final Provider<DispatchingAndroidInjector<Fragment>> fragmentAndroidInjectorProvider;

  public BaseActivity_MembersInjector(
      Provider<SharedPrefsHelper> appPrefsProvider,
      Provider<DispatchingAndroidInjector<Fragment>> fragmentAndroidInjectorProvider) {
    this.appPrefsProvider = appPrefsProvider;
    this.fragmentAndroidInjectorProvider = fragmentAndroidInjectorProvider;
  }

  public static <D extends ViewDataBinding> MembersInjector<BaseActivity<D>> create(
      Provider<SharedPrefsHelper> appPrefsProvider,
      Provider<DispatchingAndroidInjector<Fragment>> fragmentAndroidInjectorProvider) {
    return new BaseActivity_MembersInjector<D>(appPrefsProvider, fragmentAndroidInjectorProvider);
  }

  @Override
  public void injectMembers(BaseActivity<D> instance) {
    injectAppPrefs(instance, appPrefsProvider.get());
    injectFragmentAndroidInjector(instance, fragmentAndroidInjectorProvider.get());
  }

  public static <D extends ViewDataBinding> void injectAppPrefs(
      BaseActivity<D> instance, SharedPrefsHelper appPrefs) {
    instance.appPrefs = appPrefs;
  }

  public static <D extends ViewDataBinding> void injectFragmentAndroidInjector(
      BaseActivity<D> instance, DispatchingAndroidInjector<Fragment> fragmentAndroidInjector) {
    instance.fragmentAndroidInjector = fragmentAndroidInjector;
  }
}
