// Generated by Dagger (https://google.github.io/dagger).
package com.base.mvvm.common.view.base;

import androidx.databinding.ViewDataBinding;
import androidx.fragment.app.Fragment;
import androidx.lifecycle.ViewModel;
import androidx.lifecycle.ViewModelProvider;
import com.base.mvvm.common.data.local.SharedPrefsHelper;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import javax.inject.Provider;

public final class BottomTabsActivity_MembersInjector<
        V extends ViewModel, D extends ViewDataBinding>
    implements MembersInjector<BottomTabsActivity<V, D>> {
  private final Provider<SharedPrefsHelper> appPrefsProvider;

  private final Provider<DispatchingAndroidInjector<Fragment>> fragmentAndroidInjectorProvider;

  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  public BottomTabsActivity_MembersInjector(
      Provider<SharedPrefsHelper> appPrefsProvider,
      Provider<DispatchingAndroidInjector<Fragment>> fragmentAndroidInjectorProvider,
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    this.appPrefsProvider = appPrefsProvider;
    this.fragmentAndroidInjectorProvider = fragmentAndroidInjectorProvider;
    this.viewModelFactoryProvider = viewModelFactoryProvider;
  }

  public static <V extends ViewModel, D extends ViewDataBinding>
      MembersInjector<BottomTabsActivity<V, D>> create(
          Provider<SharedPrefsHelper> appPrefsProvider,
          Provider<DispatchingAndroidInjector<Fragment>> fragmentAndroidInjectorProvider,
          Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    return new BottomTabsActivity_MembersInjector<V, D>(
        appPrefsProvider, fragmentAndroidInjectorProvider, viewModelFactoryProvider);
  }

  @Override
  public void injectMembers(BottomTabsActivity<V, D> instance) {
    BaseActivity_MembersInjector.injectAppPrefs(instance, appPrefsProvider.get());
    BaseActivity_MembersInjector.injectFragmentAndroidInjector(
        instance, fragmentAndroidInjectorProvider.get());
    injectViewModelFactory(instance, viewModelFactoryProvider.get());
  }

  public static <V extends ViewModel, D extends ViewDataBinding> void injectViewModelFactory(
      BottomTabsActivity<V, D> instance, ViewModelProvider.Factory viewModelFactory) {
    instance.viewModelFactory = viewModelFactory;
  }
}
