// Generated by Dagger (https://google.github.io/dagger).
package com.base.mvvm.common.view.base;

import androidx.databinding.ViewDataBinding;
import androidx.fragment.app.Fragment;
import androidx.lifecycle.ViewModel;
import androidx.lifecycle.ViewModelProvider;
import com.google.gson.Gson;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.android.support.DaggerFragment_MembersInjector;
import javax.inject.Provider;

public final class BottomTabsFragment_MembersInjector<
        V extends ViewModel, D extends ViewDataBinding>
    implements MembersInjector<BottomTabsFragment<V, D>> {
  private final Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider;

  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  private final Provider<Gson> gsonProvider;

  public BottomTabsFragment_MembersInjector(
      Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider,
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider,
      Provider<Gson> gsonProvider) {
    this.childFragmentInjectorProvider = childFragmentInjectorProvider;
    this.viewModelFactoryProvider = viewModelFactoryProvider;
    this.gsonProvider = gsonProvider;
  }

  public static <V extends ViewModel, D extends ViewDataBinding>
      MembersInjector<BottomTabsFragment<V, D>> create(
          Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider,
          Provider<ViewModelProvider.Factory> viewModelFactoryProvider,
          Provider<Gson> gsonProvider) {
    return new BottomTabsFragment_MembersInjector<V, D>(
        childFragmentInjectorProvider, viewModelFactoryProvider, gsonProvider);
  }

  @Override
  public void injectMembers(BottomTabsFragment<V, D> instance) {
    DaggerFragment_MembersInjector.injectChildFragmentInjector(
        instance, childFragmentInjectorProvider.get());
    BaseFragment_MembersInjector.injectViewModelFactory(instance, viewModelFactoryProvider.get());
    injectGson(instance, gsonProvider.get());
  }

  public static <V extends ViewModel, D extends ViewDataBinding> void injectGson(
      BottomTabsFragment<V, D> instance, Gson gson) {
    instance.gson = gson;
  }
}
